parameter_config:
  source_type: twice-broken-power-law
  fit_params:
  - src_index
  - Nex_src
  src_index:
  - 2.3
  share_src_index: true
  src_index_range:
  - 1.0
  - 4.0
  beta_index:
  - 0.0
  beta_index_range:
  - -1.0
  - 1.0
  eta:
  - 40.0
  eta_range:
  - 2.0
  - 150.0
  P:
  - 0.4
  P_range:
  - 0.0
  - 0.5
  Nex_src_range:
  - 0.0
  - 100.0
  E0_src:
  - 1e6 GeV
  E0_src_range:
  - 1e3 GeV
  - 1e8 GeV
  diff_index: 2.5
  diff_index_range:
  - 1.0
  - 4.0
  diff_norm: 2.26e-13 GeV-1 m-2 s-1
  diff_norm_range:
  - 1e-14 GeV-1 m-2 s-1
  - 1e-11 GeV-1 m-2 s-1
  F_atmo_range:
  - 0.1 m-2 s-1
  - 0.5 m-2 s-1
  L:
  - 8e45 erg s-1
  share_L: true
  L_range:
  - 0 GeV s-1
  - 1e60 GeV s-1
  src_dec:
  - 5.7 deg
  src_ra:
  - 77.35 deg
  Enorm: 1e5 GeV
  Emin: 1e2 GeV
  Emax: 1e8 GeV
  Emin_src: 1e2 GeV
  Emax_src: 1e8 GeV
  Emin_diff: 1e2 GeV
  Emax_diff: 1e8 GeV
  z:
  - 0.3365
  Emin_det_eq: true
  Emin_det: 10 GeV
  detector_model_type:
  - IC86
  frame: detector
  MJD_min: 56917
  MJD_max: 57113
  restrict_to_list: false
  atmospheric: false
  diffuse: false
  data_bg: true
  asimov: false
  scramble_ra: false
  scramble_mjd: false
  use_event_tag: false
  logLx:
  - 43.62
prior_config:
  src_index:
    name: Ignorance
  Nex_src:
    name: Ignorance
  beta_index:
    name: NormalPrior
    mu:
    - 0.0
    sigma:
    - 0.1
  E0_src:
    name: LogNormalPrior
    mu:
    - 1e5 GeV
    sigma:
    - 3.0
  diff_index:
    name: NormalPrior
    mu: 2.52
    sigma: 0.04
  L:
    name: LogNormalPrior
    mu:
    - 1e49 GeV s-1
    sigma:
    - 3.0
  diff_flux:
    name: NormalPrior
    mu: 2.26e-13  GeV-1 s-1 m-2
    sigma: 0.19e-13 GeV-1 s-1 m-2
  atmo_flux:
    name: NormalPrior
    mu: 0.314 m-2 s-1
    sigma: 0.08 m-2 s-1
  eta:
    name: Ignorance
    mu:
    - 1.0
    sigma:
    - 1.0
  P:
    name: Ignorance
    mu:
    - 1.0
    sigma:
    - 1.0
roi_config:
  roi_type: CircularROI
  size: 5.0 deg
  apply_roi: false
  RA_min: -1.0 deg
  RA_max: 361.0 deg
  DEC_min: -91.0 deg
  DEC_max: 91.0 deg
  RA: -1.0 deg
  DEC: -91.0 deg
stan_config:
  threads_per_chain: 40
  chains: 1
  iterations: 1000
  iter_warmup: 1000
  adapt_delta: 0.8
  max_treedepth: 10
  seed: 42
ppc_config:
  n_samples: 10
  seed: 42
  directory: ppc
